@ECHO OFF

SET TEST_RUN=false
SET MONEY_AVAILABLE=true


SET REQUEST_TOKEN=%banknifty_token%
SET MARKET_CAP=%market_cap%
SET TOTAL_TRADES=%totalTrades%
SET MAX_AMOUNT=%maxAmount%

:: GTT|TWO_LEG_EXIT|CANDLE_HEIGHT|CANDLE_FLOW_WAVE|TICK_FLOW_WAVE|GENERAL
SET STRATEGY=CANDLE_HEIGHT_SHARE
SET SIMULATION=false

:: Required for CANDLE_FLOW_WAVE_SHARE Stragegy
SET CFWS_CANDLE_HEIGHT=%banknifty_ht%
SET CFWS_CANDLE_START=%banknifty%
SET CFWS_CANDLE_COLOR=%banknifty_color%
SET CFWS_DAY_HIGH=52000
SET CFWS_DAY_LOW=54000
SET CFWS_PREV_DAY_CLOSE=52700
SET CFWS_POSITION_TYPE_TO_MANAGE=buy
SET CFWS_POSITION_LOT_SIZE=15
SET CFWS_STOP_LOSS_POINTS=6000
SET CFWS_TICKER_ID=9002242
SET CFWS_TICKER_NAME=EQUITY-VOLUME
SET BANKNIFTY_BUY=%banknifty_buy%
SET BANKNIFTY_SELL=%banknifty_sell%
SET BANKNIFTY_BASELINE=INDEX

kite.exe >> om-%market_cap%_6_dec.log